# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[(b'1', b'Primero'), (b'2', b'Segundo'), (b'3', b'Tercero'), (b'4', b'Cuarto'), (b'5', b'Quinto'), (b'6', b'Sexto')], max_length=1, verbose_name=b'Grado')),
                ('section', models.CharField(max_length=1, verbose_name=b'Seccion')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_time', models.PositiveSmallIntegerField(verbose_name=b'Minutos de recreo')),
                ('classrooms', models.PositiveSmallIntegerField(verbose_name=b'Cantidad de aulas')),
                ('hour_duration', models.PositiveSmallIntegerField(verbose_name='Minutos de duraci\xf3n de las horas acad\xe9micas')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Cantidad de horas acad\xe9micas')),
                ('level', models.CharField(choices=[(b'Primaria', b'Primaria'), (b'Secundaria', b'Secundaria')], max_length=10, verbose_name=b'Nivel')),
                ('name', models.CharField(max_length=75, verbose_name=b'Nombre')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name=b'Colegio'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([('grade', 'school', 'section')]),
        ),
    ]
